In [19]:
# load library
import csv
import time
from selenium import webdriver
import pandas as pd
from bs4 import BeautifulSoup

In [20]:
# chromedriver url link
driver=webdriver.Chrome("./chromedriver")

In [21]:
# create dictionary
jobs={"roles":[],
     "companies":[],
     "locations":[],
     "experience":[],
     "skills":[],
     "salary":[],
     "job_desc":[]}

In [24]:
# link of website you want to scrap
for i in range(1):
    driver.get("https://www.naukri.com/data-scientist-jobs-{}".format(i))
    time.sleep(3)
    lst=driver.find_elements_by_css_selector(".jobTuple.bgWhite.br4.mb-8")
    
    # scrape the data from website
    for job in lst:
        driver.implicitly_wait(10)
        role=job.find_element_by_css_selector("a.title.fw500.ellipsis").text
        company=job.find_element_by_css_selector("a.subTitle.ellipsis.fleft").text
        location=job.find_element_by_css_selector(".fleft.grey-text.br2.placeHolderLi.location").text
        exp=job.find_element_by_css_selector(".fleft.grey-text.br2.placeHolderLi.experience").text
        skills=job.find_element_by_css_selector(".tags.has-description").text
        salary=job.find_element_by_css_selector(".fleft.grey-text.br2.placeHolderLi.salary").text
        job_desc=job.find_element_by_css_selector(".job-description.fs12.grey-text").text
        jobs["roles"].append(role)
        jobs["companies"].append(company)
        jobs["locations"].append(location)
        jobs["experience"].append(exp)
        jobs["skills"].append(skills)
        jobs["salary"].append(salary)
        jobs["job_desc"].append(job_desc)

In [5]:
# tranform data into dataframe
data=pd.DataFrame.from_dict(jobs)
data.head(10)

,roles,companies,locations,experience,skills,salary,job_desc
0,Data Scientist/Analyst - Machine Learning/Deep...,EchoIndia,Delhi,3-6 Yrs,IT Skills\nPython\nMachine Learning\nTableau\n...,Not disclosed,- Strong experience in statistical models and ...
1,"Data Scientist, Machine Learning",Fractal Analytics Ltd,Bengaluru,3-7 Yrs,Supply chain management\nLinux\nRF\nRDBMS\nBfs...,Not disclosed,Experience of working on end-to-end data scien...
2,"Data Scientist, I",iXplore Technologies,Bengaluru,0-2 Yrs,IT Skills\nSoftware Development\nMachine Learn...,Not disclosed,"Bachelors degree, Masters or PhD in statistics..."
3,Explore job openings on Data Scientist!!,Bristlecone India Limited,"Pune, Mumbai, Bengaluru",4-9 Yrs,IT Skills\nPython\nData Science\nMachine Learn...,"3,00,000 - 8,00,000 PA.",Hands-on python programming with experience de...
4,Inviting Application For Data Scientist - Mana...,GENPACT India Private Limited,Bengaluru,6-11 Yrs,Machine Learning\nStatistics\nDeep Learning\nR...,Not disclosed,"With a startup spirit and 90, 000+ curious and..."
5,Senior Principal Software Engineer - IT (Data ...,Dell International Services IndiaPrivate Limited,Bengaluru,10-12 Yrs,IT Skills\nPython\nTesting\nMachine Learning\n...,Not disclosed,"Proficiency in Python or R, Tableu especially ..."
6,Data Scientist/Analyst – IT Department,Nandan Denim Limited,Ahmedabad,7-8 Yrs,Data Analysis\nStatistical Modeling\nPredictiv...,Not disclosed,Hands on experience in one or more databases l...
7,Data Scientist/Analyst – IT Department,Nandan Denim Limited,Ahmedabad,7-8 Yrs,Data Analysis\nStatistical Modeling\nPredictiv...,Not disclosed,Hands on experience in one or more databases l...
8,"Data Scientist, Machine Learning",Fractal.ai,Bengaluru,3-7 Yrs,Supply chain management\nLinux\nRF\nRDBMS\nBfs...,Not disclosed,Experience of working on end-to-end data scien...
9,Assistant Manager/ Manager/ Data Scientist - P...,Huquo Consulting Pvt. Ltd,Bengaluru,3-8 Yrs,Data Science\nPredictive Modeling\nNLP\nData S...,Not disclosed,Experience in machine learning algorithm devel...

In [6]:
data.shape

(3000, 7)

In [7]:
data.to_csv('C:/Users/hp/Desktop/web scrape/second/second.csv',index=True)